[project]
name = "edurec"
version = "0.1.0"
description = "The objective of this Master's Thesis is to develop a recommendation system for e-learning based on a benchmark dataset, which will allow evaluating its performance in comparison with previous models."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "pandas<3.0.0",
  "scikit-learn>=1.9.0",
  "torch>=2.11.0",
  "matplotlib>=3.10.1",
  "torchmetrics>=1.8.0",
  "lightning[extra]>=2.5.2",
  "openpyxl>=3.1.5",
  "scipy<1.13.0",
  "scikit-posthocs>=0.11.4",
  "pydantic>=2.11.9",
  "typer>=0.26.7",
  "recbole>=1.2.0",
  "pandas-stubs>=2.3.3.260113",
  "ray[tune]>=2.53.0",
  "numpy<2.0.0",
  "kmeans-pytorch>=0.3",
  "torch-geometric>=2.8.0",
  "safetensors>=0.8.0",
  "joblib>=1.5.3",
  "sentence-transformers>=5.3.0",
  "optuna>=4.9.0",
  "kagglehub>=1.0.2",
]

[dependency-groups]
dev = ["wandb>=0.24.0"]


[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "-v"
# Ignore PyG warnings in tests
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore:.*torch_geometric.distributed.*:DeprecationWarning",
  "ignore:.*torch.jit.script.*:DeprecationWarning",
]

[project.scripts]
edurec = "edurec.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
