arch: kg_rnn
dropout: 0.15
emb_dim: 128
gnn_dropout: 0.15
gnn_heads: 4
gnn_layers: 1
graph_mode: kg
has_history: true
hidden_dims:
  - 256
  - 128
kg_edge_types: []
kg_node_counts: {}
num_item_dense_feats: 486
num_item_text_feats: 384
num_items: 1609
num_user_dense_feats: 0
num_users: 4741
rnn_hidden_dim: 256
rnn_layers: 2
rnn_type: gru
use_interaction_features: true
use_item_bias: false
use_text_features: true
use_time_features: true
