adaptive_k: false
alpha: 0.01
dropout: 0.3
edge_dropout: 0.0
emb_dim: 256
ff_dim: 2048
gnn_layers: 1
graph_mode: lightgcn
has_history: true
hidden_dims:
- 512
item_cat_cardinalities:
- 18
- 1178
loss_reduction: mean
lr: 0.0005
n_blocks: 2
n_heads: 16
num_ctx_feats: 386
num_item_dense_feats: 384
num_item_text_feats: 384
num_items: 2746
num_user_dense_feats: 0
num_user_text_feats: 0
num_users: 3951
scorer_type: mlp
temperature: 0.15
topks:
- 5
- 10
- 20
use_context: true
use_gcl: true
use_item_bias: true
use_item_features: true
use_seq_encoder: true
use_text_features: true
use_user_features: true
user_cat_cardinalities:
- 10
- 2
- 110
weight_decay: 0.001
